/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ajayk
 */
public class MagicMath extends javax.swing.JFrame {
    int given1;
    int given2;
    int answer1;
    int given3;
    int given4;
    int answer2;
    double given5;
    double given6;
    double answer3;
    double given7;
    double given8;
    double answer4;
    double given9;
    double answer5;
    double given10;
    double answer6;
    double given11;
    double answer7;
    double given12;
    double answer8;
    
    /**
     * Creates new form MagicMath
     */
    public MagicMath() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Question1_lbl = new javax.swing.JLabel();
        Given2_txt = new javax.swing.JTextField();
        Given1_txt = new javax.swing.JTextField();
        Question1_button = new javax.swing.JButton();
        Question2_lbl = new javax.swing.JLabel();
        Given3_txt = new javax.swing.JTextField();
        Given4_txt = new javax.swing.JTextField();
        Question2_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Given6_txt = new javax.swing.JTextField();
        Given5_txt = new javax.swing.JTextField();
        Question3_button = new javax.swing.JButton();
        Question4_lbl = new javax.swing.JLabel();
        Given7_txt = new javax.swing.JTextField();
        Given8_txt = new javax.swing.JTextField();
        Question5_lbl = new javax.swing.JLabel();
        Given9_txt = new javax.swing.JTextField();
        Question4_button = new javax.swing.JButton();
        Question5_button = new javax.swing.JButton();
        Question6_lbl = new javax.swing.JLabel();
        Question6_button = new javax.swing.JButton();
        Given10_txt = new javax.swing.JTextField();
        Question7_lbl = new javax.swing.JLabel();
        Given11_txt = new javax.swing.JTextField();
        Question7_button = new javax.swing.JButton();
        Question8_lbl = new javax.swing.JLabel();
        Question8_button = new javax.swing.JButton();
        Given12_txt = new javax.swing.JTextField();
        Answer2_lbl = new javax.swing.JLabel();
        Answer1_lbl = new javax.swing.JLabel();
        Answer3_lbl = new javax.swing.JLabel();
        Answer5_lbl = new javax.swing.JLabel();
        Answer6_lbl = new javax.swing.JLabel();
        Answer7_lbl = new javax.swing.JLabel();
        Answer4_lbl = new javax.swing.JLabel();
        Answer8_lbl = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel1.setText("Magical Math Methods");

        Question1_lbl.setText("Enter two numbers. The program will display the largest of the two numbers:");

        Given2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Given2_txtActionPerformed(evt);
            }
        });

        Given1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Given1_txtActionPerformed(evt);
            }
        });

        Question1_button.setText("Go");
        Question1_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question1_buttonActionPerformed(evt);
            }
        });

        Question2_lbl.setText("Enter two numbers. The program will display the smallest of the two numbers:");

        Given3_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Given3_txtActionPerformed(evt);
            }
        });

        Given4_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Given4_txtActionPerformed(evt);
            }
        });

        Question2_button.setText("Go");
        Question2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2_buttonActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter two numbers. The programs will display the first number to the power of the second:");

        Given6_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Given6_txtActionPerformed(evt);
            }
        });

        Given5_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Given5_txtActionPerformed(evt);
            }
        });

        Question3_button.setText("Go");
        Question3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3_buttonActionPerformed(evt);
            }
        });

        Question4_lbl.setText("Enter the length of two sides of a right angle triangle. The program will display the hypotenuse of the triangle:");

        Question5_lbl.setText("Enter a decimal value. The program will display the value rounded down to the nearest integer: ");

        Question4_button.setText("Go");
        Question4_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question4_buttonActionPerformed(evt);
            }
        });

        Question5_button.setText("Go");
        Question5_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question5_buttonActionPerformed(evt);
            }
        });

        Question6_lbl.setText("Enter a decimal value. The program will display the value rounded up to the nearest integer: ");

        Question6_button.setText("Go");
        Question6_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question6_buttonActionPerformed(evt);
            }
        });

        Question7_lbl.setText("Enter an integer. This program will display the square root of the integer:");

        Question7_button.setText("Go");
        Question7_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question7_buttonActionPerformed(evt);
            }
        });

        Question8_lbl.setText("Enter an angle in degrees. The program will display the angle in radians: ");

        Question8_button.setText("Go");
        Question8_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question8_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Given1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Given2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question1_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(Given3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Given4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question2_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Given5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Given6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question3_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Question4_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Question2_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Question1_lbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(Given7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Given8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question4_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer4_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(Given9_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question5_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer5_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(Given10_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question6_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer6_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question7_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Given11_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(Question7_button)
                        .addGap(130, 130, 130)
                        .addComponent(Answer7_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question5_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question8_lbl))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(Given12_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(Question8_button)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Answer8_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Question6_lbl))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Question1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Given2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Given1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Question1_button))
                        .addGap(28, 28, 28)
                        .addComponent(Question2_lbl)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Given3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Given4_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Question2_button))
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel2))
                                    .addComponent(Answer2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Given6_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Given5_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Question3_button)))
                            .addComponent(Answer3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(Question4_lbl)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Given7_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Given8_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Question4_button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(Question5_lbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Given9_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Question5_button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addComponent(Question6_lbl))
                                    .addComponent(Answer5_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(Question6_button)
                                                    .addComponent(Given10_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addComponent(Question7_lbl))
                                            .addComponent(Answer6_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(Given11_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Question7_button)))
                                    .addComponent(Answer7_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addComponent(Question8_lbl))
                            .addComponent(Answer4_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Answer1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Question8_button)
                        .addComponent(Given12_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Answer8_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Given2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Given2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Given2_txtActionPerformed

    private void Given1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Given1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Given1_txtActionPerformed

    private void Question1_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question1_buttonActionPerformed
        given1 = Integer.parseInt(Given1_txt.getText());
        given2 = Integer.parseInt(Given2_txt.getText());
        
        answer1 = Math.max(given1, given2);
        Answer1_lbl.setText(String.valueOf("Max = " + answer1));
    }//GEN-LAST:event_Question1_buttonActionPerformed

    private void Given3_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Given3_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Given3_txtActionPerformed

    private void Given4_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Given4_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Given4_txtActionPerformed

    private void Question2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2_buttonActionPerformed
       given3 = Integer.parseInt(Given3_txt.getText());
       given4 = Integer.parseInt(Given4_txt.getText());
        
       answer2 = Math.min(given3, given4);
       Answer2_lbl.setText(String.valueOf("Min = " + answer2));
    }//GEN-LAST:event_Question2_buttonActionPerformed

    private void Given6_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Given6_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Given6_txtActionPerformed

    private void Given5_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Given5_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Given5_txtActionPerformed

    private void Question3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3_buttonActionPerformed
      given5 = Double.parseDouble(Given5_txt.getText());
      given6 = Double.parseDouble(Given6_txt.getText());
        
      answer3 = Math.pow(given5, given6);
      Answer3_lbl.setText(String.valueOf("Answer = " + answer3));  
    }//GEN-LAST:event_Question3_buttonActionPerformed

    private void Question8_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question8_buttonActionPerformed
        given12 = Double.parseDouble(Given12_txt.getText());
        
        answer8 = Math.toRadians(given12);
        Answer8_lbl.setText(String.valueOf("Radians = " + answer8));
        
        
    }//GEN-LAST:event_Question8_buttonActionPerformed

    private void Question4_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question4_buttonActionPerformed
        given7 = Double.parseDouble(Given7_txt.getText());
        given8 = Double.parseDouble(Given8_txt.getText());
        
        answer4 = Math.hypot(given7, given8);
        Answer4_lbl.setText(String.valueOf("Hypotenuse = " + answer4));
    }//GEN-LAST:event_Question4_buttonActionPerformed

    private void Question5_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question5_buttonActionPerformed
        given9 = Double.parseDouble(Given9_txt.getText());
        
        answer5 = Math.floor(given9);
        Answer5_lbl.setText(String.valueOf("Rounded down" +  answer5));
    }//GEN-LAST:event_Question5_buttonActionPerformed

    private void Question6_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question6_buttonActionPerformed
       given10 = Double.parseDouble(Given10_txt.getText());
        
       answer6 = Math.ceil(given10);
       Answer6_lbl.setText(String.valueOf("Rounded up = " + answer6)); 
    }//GEN-LAST:event_Question6_buttonActionPerformed

    private void Question7_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question7_buttonActionPerformed
        given11 = Double.parseDouble(Given11_txt.getText());
        
        answer7 = Math.sqrt(given11);
        Answer7_lbl.setText(String.valueOf("Square Root = " + answer7));
    }//GEN-LAST:event_Question7_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagicMath.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagicMath().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Answer1_lbl;
    private javax.swing.JLabel Answer2_lbl;
    private javax.swing.JLabel Answer3_lbl;
    private javax.swing.JLabel Answer4_lbl;
    private javax.swing.JLabel Answer5_lbl;
    private javax.swing.JLabel Answer6_lbl;
    private javax.swing.JLabel Answer7_lbl;
    private javax.swing.JLabel Answer8_lbl;
    private javax.swing.JTextField Given10_txt;
    private javax.swing.JTextField Given11_txt;
    private javax.swing.JTextField Given12_txt;
    private javax.swing.JTextField Given1_txt;
    private javax.swing.JTextField Given2_txt;
    private javax.swing.JTextField Given3_txt;
    private javax.swing.JTextField Given4_txt;
    private javax.swing.JTextField Given5_txt;
    private javax.swing.JTextField Given6_txt;
    private javax.swing.JTextField Given7_txt;
    private javax.swing.JTextField Given8_txt;
    private javax.swing.JTextField Given9_txt;
    private javax.swing.JButton Question1_button;
    private javax.swing.JLabel Question1_lbl;
    private javax.swing.JButton Question2_button;
    private javax.swing.JLabel Question2_lbl;
    private javax.swing.JButton Question3_button;
    private javax.swing.JButton Question4_button;
    private javax.swing.JLabel Question4_lbl;
    private javax.swing.JButton Question5_button;
    private javax.swing.JLabel Question5_lbl;
    private javax.swing.JButton Question6_button;
    private javax.swing.JLabel Question6_lbl;
    private javax.swing.JButton Question7_button;
    private javax.swing.JLabel Question7_lbl;
    private javax.swing.JButton Question8_button;
    private javax.swing.JLabel Question8_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
